name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        python-version: [3.8, 3.9]
        poetry-version: [1.1.4]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry ${{ matrix.poetry-version }}
      run: pip install poetry==${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install
    - name: remove shared libraries
      run: poetry run python ./tasks.py clean
    - name: Run checks and lint code
      run: poetry run python ./tasks.py lint
    - name: Run tests
      run: poetry run python ./tasks.py test
    - name: Create coverage xml report
      run: poetry run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
